// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT_ywqm__-41MAbcR-TpJazB9mu_6l5d4',
    appId: '1:562989451896:web:37051798ee441a11127b8d',
    messagingSenderId: '562989451896',
    projectId: 'flutter-chat-app-732e5',
    authDomain: 'flutter-chat-app-732e5.firebaseapp.com',
    storageBucket: 'flutter-chat-app-732e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5lKJIOG3_ezAR78x5hgcFpRv5ouNliRs',
    appId: '1:562989451896:android:f9e79477bd7ec9bb127b8d',
    messagingSenderId: '562989451896',
    projectId: 'flutter-chat-app-732e5',
    storageBucket: 'flutter-chat-app-732e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VPl30DjdsuIGPPRvBKffF8Jz_jfX9Z4',
    appId: '1:562989451896:ios:9603d3f0ef4ccb42127b8d',
    messagingSenderId: '562989451896',
    projectId: 'flutter-chat-app-732e5',
    storageBucket: 'flutter-chat-app-732e5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
